apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contact-moj-ingress
  namespace: contact-moj-production
  annotations:
    # This forces all 503 error page to be served from the application
    nginx.ingress.kubernetes.io/custom-http-errors: "503"
    external-dns.alpha.kubernetes.io/set-identifier: contact-moj-ingress-contact-moj-production-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  ingressClassName: default
  tls:
    - hosts:
        - contact-moj.service.justice.gov.uk
      secretName: contact-moj-certificate
  rules:
    - host: contact-moj.service.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: contact-moj-service
                port:
                  number: 3000
