apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: contact-moj-ingress
  namespace: contact-moj-production
spec:
  tls:
    - hosts:
        - contact-moj.service.justice.gov.uk
      secretName: contact-moj-certificate
  rules:
    - host: contact-moj.service.justice.gov.uk
      http:
        paths:
          - path: /
            backend:
              serviceName: contact-moj-service
              servicePort: 3000
