apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contact-moj-ingress
  namespace: contact-moj-production
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: contact-moj-ingress-contact-moj-production-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecAuditEngine On
      SecRuleEngine DetectionOnly
      SecDefaultAction "phase:2,pass,log,tag:github_team=central-digital-product-team,tag:namespace=contact-moj-production"
spec:
  ingressClassName: modsec
  tls:
    - hosts:
        - contact-moj.service.justice.gov.uk
      secretName: contact-moj-certificate
  rules:
    - host: contact-moj.service.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: contact-moj-service
                port:
                  number: 3000
